### ISSUE TITLE
Windows - 10: always : panic: The parameter is incorrect.

### ISSUE THREAD

**Issue by rsrini7** [thehowl/claws#15]
```
        panic: The parameter is incorrect.
        panic: The parameter is incorrect.

goroutine 1 [running]:
github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.move_cursor(0x2, 0x26)
        /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/termbox_windows.go:592 +0x75 github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.Flush(0xc000000000, 0x0)
        /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/api_windows.go:120 +0x10c
github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.Close()
        /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/api_windows.go:78 +0x39
github.com/thehowl/claws/vendor/github.com/jroimartin/gocui.(*Gui).Close(0xc0420f8090)
        /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/jroimartin/gocui/gui.go:96 +0x27
panic(0x67ca40, 0xc0421b0000)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x237
github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.move_cursor(0x2, 0x26)
        /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/termbox_windows.go:592 +0x75 github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.clear()
        /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/termbox_windows.go:629 +0x121

github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.update_size_maybe()
        /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/termbox_windows.go:451 +0xc5 github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.Clear(0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/api_windows.go:187 +0x41
github.com/thehowl/claws/vendor/github.com/jroimartin/gocui.(*Gui).flush(0xc0420f8090, 0x0, 0x0)
        /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/jroimartin/gocui/gui.go:423 +0x43
github.com/thehowl/claws/vendor/github.com/jroimartin/gocui.(*Gui).MainLoop(0xc0420f8090, 0x0, 0x0)
        /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/jroimartin/gocui/gui.go:384 +0x22b
main.main()
        /home/travis/gopath/src/github.com/thehowl/claws/main.go:33 +0x1da
```

**Comment by rsrini7** [comment]
> panic: The parameter is incorrect.
> panic: The parameter is incorrect.
> 
> goroutine 1 [running]:
> github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.move_cursor(0x2, 0x26)
> /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/termbox_windows.go:592 +0x75 github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.Flush(0xc000000000, 0x0)
> /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/api_windows.go:120 +0x10c
> github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.Close()
> /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/api_windows.go:78 +0x39
> github.com/thehowl/claws/vendor/github.com/jroimartin/gocui.(*Gui).Close(0xc0420f8090)
> /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/jroimartin/gocui/gui.go:96 +0x27
> panic(0x67ca40, 0xc0421b0000)
> /home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x237
> github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.move_cursor(0x2, 0x26)
> /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/termbox_windows.go:592 +0x75 github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.clear()
> /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/termbox_windows.go:629 +0x121
> 
> github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.update_size_maybe()
> /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/termbox_windows.go:451 +0xc5 github.com/thehowl/claws/vendor/github.com/nsf/termbox-go.Clear(0x0, 0x0, 0x0)
> /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/nsf/termbox-go/api_windows.go:187 +0x41
> github.com/thehowl/claws/vendor/github.com/jroimartin/gocui.(*Gui).flush(0xc0420f8090, 0x0, 0x0)
> /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/jroimartin/gocui/gui.go:423 +0x43
> github.com/thehowl/claws/vendor/github.com/jroimartin/gocui.(*Gui).MainLoop(0xc0420f8090, 0x0, 0x0)
> /home/travis/gopath/src/github.com/thehowl/claws/vendor/github.com/jroimartin/gocui/gui.go:384 +0x22b
> main.main()
> /home/travis/gopath/src/github.com/thehowl/claws/main.go:33 +0x1da

This is happening only in conemu - cmder

**Comment by thehowl** [comment]
Issue seems to be the following: https://github.com/nsf/termbox-go/issues/125 and should have been fixed in Gocui with this commit: https://github.com/Alkorin/gocui/commit/72ea818abba80ad76560f38417f56efe31c60716 .

I've updated the gocui dependencies - could you try with the latest release? https://github.com/thehowl/claws/releases/tag/0.3.2

**Comment by rsrini7** [comment]
Perfect. Working well. Thanks for the fix. I thought its fix from gocui. 
I am facing same issues with all other gocui based cli tools. Better to push to gocui.

**Comment by thehowl** [comment]
Yeah, it has been fixed from gocui and it is on the latest version, but it may take a while to propagate to other gocui tools. 

Thank you for your report!
