### ISSUE TITLE
Add a new letter (maybe it can be "C") to clear history messages.

### ISSUE THREAD

**Issue by WhitePaper233** [thehowl/claws#17]
Add a new letter (maybe it can be "C") to clear history messages, just like "clear" command in bash.

**Comment by thehowl** [comment]
hmm, sounds good. I would first look into whether we can integrate this as `CTRL+L` (similar to how you can do it in pretty much all shell terminals without using the clear command), but otherwise C is good. Can take a look next time I decide to focus on this a bit

**Comment by thehowl** [comment]
Added with 17c8eae16d031a6080bb5429fa6deef7dc286131
